# Generated by Django 4.2.16 on 2026-06-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'affectations',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('entreprise', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('stagiaire', 'Stagiaire'), ('tuteur', 'Tuteur'), ('administrateur', 'Administrateur')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.IntegerField()),
                ('date_debut_sem', models.DateField()),
                ('date_fin_sem', models.DateField()),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='en_attente', max_length=20)),
                ('commentaire_tuteur', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='api.stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='api.user')),
            ],
            options={
                'db_table': 'rapports',
                'unique_together': {('stagiaire', 'stage', 'semaine')},
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('fichier', 'Fichier'), ('lien', 'Lien')], max_length=10)),
                ('url_ou_chemin', models.CharField(max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='api.rapport')),
            ],
            options={
                'db_table': 'livrables',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('appreciation', models.TextField()),
                ('points_forts', models.TextField(blank=True, null=True)),
                ('points_ameliorer', models.TextField(blank=True, null=True)),
                ('date_redaction', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='api.affectation')),
            ],
            options={
                'db_table': 'evaluations',
            },
        ),
        migrations.AddField(
            model_name='affectation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='api.stage'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_stagiaire', to='api.user'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_tuteur', to='api.user'),
        ),
    ]
